name: Book

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: '0.4.52'

      - name: Install mdbook-mermaid
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-mermaid
          version: "0.16.2"

      - name: Install mdbook-cmdrun
        uses: baptiste0928/cargo-install@v3
        with:
          crate: mdbook-cmdrun
      
      - name: Build the suite to retrieve its features
        working-directory: rust
        run: cargo build

      - working-directory: book
        run: ./build.sh

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
